services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - "./shared:/shared:delegated"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - "./shared:/shared:delegated"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
