name: CI/CD Pipeline

on:
  push:
    branches:
      - features/azure
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.x"

      # Install backend dependencies and build
      - name: Backend - Install and Build
        run: |
          cd backend
          npm install
          npm run build

      # Install frontend dependencies and build
      - name: Frontend - Install and Build
        run: |
          cd frontend
          npm install
          npm run build

      # Build Docker image and push to Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build -f Dockerfile.prod -t darkpencil1/art-hosting-site .
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push darkpencil1/art-hosting-site

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Docker Hub image to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp create --resource-group WebAppResourceGroup \
                           --plan WebAppServicePlan \
                           --name art-hosting-site \
                           --deployment-container-image-name darkpencil1/art-hosting-site:latest
          az webapp config set --resource-group WebAppResourceGroup \
                               --name art-hosting-site \
                               --linux-fx-version "DOCKER|darkpencil1/art-hosting-site:latest"
